import type { PseudocodeBlock } from '@/core/engine/types'

/**
 * Pseudocode for lecture 11 (Red-Black Trees), transcribed from the slides /
 * CLRS ch. 13 with parallel Python. 1-based line numbers match the `code`
 * values emitted by the tracer in rbtree.ts.
 */

export const leftRotateBlock: PseudocodeBlock = {
  id: 'leftRotate',
  titleEn: 'Left-Rotate(T, x)',
  titleHe: 'סיבוב שמאלה',
  kind: 'helper',
  lines: [
    'Left-Rotate(T, x)',
    '    y = right[x]                 // y = x’s right child',
    '    right[x] = left[y]           // y’s left subtree → x’s right',
    '    if left[y] ≠ NIL: p[left[y]] = x',
    '    p[y] = p[x]                  // relink x’s parent to y',
    '    if p[x] = NIL: root[T] = y',
    '    elseif x = left[p[x]]: left[p[x]] = y',
    '    else: right[p[x]] = y',
    '    left[y] = x                  // put x on y’s left',
    '    p[x] = y',
  ],
  pythonLines: [
    'def left_rotate(T, x):',
    '    y = x.right',
    '    x.right = y.left',
    '    if y.left is not T.nil: y.left.p = x',
    '    y.p = x.p',
    '    if x.p is T.nil: T.root = y',
    '    elif x is x.p.left: x.p.left = y',
    '    else: x.p.right = y',
    '    y.left = x',
    '    x.p = y',
  ],
}

export const rightRotateBlock: PseudocodeBlock = {
  id: 'rightRotate',
  titleEn: 'Right-Rotate(T, x)',
  titleHe: 'סיבוב ימינה',
  kind: 'helper',
  lines: [
    'Right-Rotate(T, x)',
    '    y = left[x]                  // y = x’s left child',
    '    left[x] = right[y]           // y’s right subtree → x’s left',
    '    if right[y] ≠ NIL: p[right[y]] = x',
    '    p[y] = p[x]                  // relink x’s parent to y',
    '    if p[x] = NIL: root[T] = y',
    '    elseif x = right[p[x]]: right[p[x]] = y',
    '    else: left[p[x]] = y',
    '    right[y] = x                 // put x on y’s right',
    '    p[x] = y',
  ],
  pythonLines: [
    'def right_rotate(T, x):',
    '    y = x.left',
    '    x.left = y.right',
    '    if y.right is not T.nil: y.right.p = x',
    '    y.p = x.p',
    '    if x.p is T.nil: T.root = y',
    '    elif x is x.p.right: x.p.right = y',
    '    else: x.p.left = y',
    '    y.right = x',
    '    x.p = y',
  ],
}

export const rbInsertBlock: PseudocodeBlock = {
  id: 'rbInsert',
  titleEn: 'RB-Insert(T, z)',
  titleHe: 'הכנסה אדומה-שחורה',
  kind: 'main',
  lines: [
    'RB-Insert(T, z)',
    '    y = NIL;  x = root[T]',
    '    while x ≠ NIL',
    '        y = x',
    '        if key[z] < key[x]: x = left[x]',
    '        else: x = right[x]',
    '    p[z] = y',
    '    if y = NIL: root[T] = z',
    '    elseif key[z] < key[y]: left[y] = z',
    '    else: right[y] = z',
    '    left[z] = right[z] = NIL;  color[z] = RED',
    '    RB-Insert-Fixup(T, z)',
  ],
  pythonLines: [
    'def rb_insert(T, z):',
    '    y, x = T.nil, T.root',
    '    while x is not T.nil:',
    '        y = x',
    '        x = x.left if z.key < x.key else x.right',
    '    z.p = y',
    '    if y is T.nil: T.root = z',
    '    elif z.key < y.key: y.left = z',
    '    else: y.right = z',
    '    z.left = z.right = T.nil; z.color = RED',
    '    rb_insert_fixup(T, z)',
  ],
}

export const rbInsertFixupBlock: PseudocodeBlock = {
  id: 'rbInsertFixup',
  titleEn: 'RB-Insert-Fixup(T, z)',
  titleHe: 'תיקון לאחר הכנסה',
  kind: 'main',
  lines: [
    'RB-Insert-Fixup(T, z)',
    '    while color[p[z]] = RED',
    '        if p[z] = left[p[p[z]]]',
    '            y = right[p[p[z]]]            // y = "uncle"',
    '            if color[y] = RED                       // Case 1',
    '                color[p[z]]=color[y]=BLACK; color[p[p[z]]]=RED; z=p[p[z]]',
    '            else',
    '                if z = right[p[z]]                  // Case 2',
    '                    z = p[z];  Left-Rotate(T, z)',
    '                color[p[z]]=BLACK; color[p[p[z]]]=RED   // Case 3',
    '                Right-Rotate(T, p[p[z]])',
    '        else  // mirror: swap "left" ↔ "right"',
    '    color[root[T]] = BLACK',
  ],
  pythonLines: [
    'def rb_insert_fixup(T, z):',
    '    while z.p.color == RED:',
    '        if z.p is z.p.p.left:',
    '            y = z.p.p.right                 # uncle',
    '            if y.color == RED:              # Case 1',
    '                z.p.color = y.color = BLACK; z.p.p.color = RED; z = z.p.p',
    '            else:',
    '                if z is z.p.right:          # Case 2',
    '                    z = z.p; left_rotate(T, z)',
    '                z.p.color = BLACK; z.p.p.color = RED   # Case 3',
    '                right_rotate(T, z.p.p)',
    '        else:  # mirror',
    '    T.root.color = BLACK',
  ],
}

export const rbDeleteBlock: PseudocodeBlock = {
  id: 'rbDelete',
  titleEn: 'RB-Delete(T, z)',
  titleHe: 'מחיקה אדומה-שחורה',
  kind: 'main',
  lines: [
    'RB-Delete(T, z)',
    '    y = z;  y-color = color[y]',
    '    if left[z] = NIL',
    '        x = right[z];  Transplant(T, z, right[z])',
    '    elseif right[z] = NIL',
    '        x = left[z];   Transplant(T, z, left[z])',
    '    else  y = Tree-Minimum(right[z]);  y-color = color[y];  x = right[y]',
    '        if p[y] = z: p[x] = y',
    '        else: Transplant(T, y, right[y]); right[y]=right[z]; p[right[y]]=y',
    '        Transplant(T, z, y); left[y]=left[z]; p[left[y]]=y; color[y]=color[z]',
    '    if y-color = BLACK: RB-Delete-Fixup(T, x)',
  ],
  pythonLines: [
    'def rb_delete(T, z):',
    '    y = z; y_color = y.color',
    '    if z.left is T.nil:',
    '        x = z.right; transplant(T, z, z.right)',
    '    elif z.right is T.nil:',
    '        x = z.left;  transplant(T, z, z.left)',
    '    else:  y = tree_minimum(z.right); y_color = y.color; x = y.right',
    '        if y.p is z: x.p = y',
    '        else: transplant(T, y, y.right); y.right = z.right; y.right.p = y',
    '        transplant(T, z, y); y.left = z.left; y.left.p = y; y.color = z.color',
    '    if y_color == BLACK: rb_delete_fixup(T, x)',
  ],
}

export const rbDeleteFixupBlock: PseudocodeBlock = {
  id: 'rbDeleteFixup',
  titleEn: 'RB-Delete-Fixup(T, x)',
  titleHe: 'תיקון לאחר מחיקה',
  kind: 'main',
  lines: [
    'RB-Delete-Fixup(T, x)',
    '    while x ≠ root[T] and color[x] = BLACK',
    '        if x = left[p[x]]',
    '            w = right[p[x]]                         // w = sibling',
    '            if color[w] = RED                                  // Case 1',
    '                color[w]=BLACK; color[p[x]]=RED; Left-Rotate(T,p[x]); w=right[p[x]]',
    '            if color[left[w]]=BLACK and color[right[w]]=BLACK   // Case 2',
    '                color[w]=RED;  x=p[x]',
    '            else',
    '                if color[right[w]]=BLACK                        // Case 3',
    '                    color[left[w]]=BLACK; color[w]=RED; Right-Rotate(T,w); w=right[p[x]]',
    '                color[w]=color[p[x]]; color[p[x]]=BLACK         // Case 4',
    '                color[right[w]]=BLACK; Left-Rotate(T,p[x]); x=root[T]',
    '        else  // mirror: swap "left" ↔ "right"',
    '    color[x] = BLACK',
  ],
  pythonLines: [
    'def rb_delete_fixup(T, x):',
    '    while x is not T.root and x.color == BLACK:',
    '        if x is x.p.left:',
    '            w = x.p.right                  # sibling',
    '            if w.color == RED:             # Case 1',
    '                w.color=BLACK; x.p.color=RED; left_rotate(T,x.p); w=x.p.right',
    '            if w.left.color==BLACK and w.right.color==BLACK:   # Case 2',
    '                w.color=RED; x=x.p',
    '            else:',
    '                if w.right.color==BLACK:   # Case 3',
    '                    w.left.color=BLACK; w.color=RED; right_rotate(T,w); w=x.p.right',
    '                w.color=x.p.color; x.p.color=BLACK             # Case 4',
    '                w.right.color=BLACK; left_rotate(T,x.p); x=T.root',
    '        else:  # mirror',
    '    x.color = BLACK',
  ],
}
